exemptLabels:
  - pinned
  - feature
  - next
  - help wanted
  - good first issue
  - IE
  - security
  - greenkeeper
  - bug

exemptMilestones: true

staleLabel: Stale

pulls:
  daysUntilStale: 30
  markComment: >
    This pull request has been automatically marked as stale because it has not had
    recent activity. It will be closed if no further activity occurs. Thank you
    for your contributions.
