version: "2"
plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      config: .eslintrc.js
exclude_patterns:
  - "dist/"
  - "dist-modules/"
  - "test/"
  - "**/node_modules/"
  - "**/vendor/"
  - "**/docs/"
