env:
  global:
    - CC_TEST_REPORTER_ID: $CC_TEST_REPORTER_ID
language: node_js
node_js:
  - "9"
  - "8"
  - "7"
  - "6"
before_install:
- npm install -g npm
- npm install -g greenkeeper-lockfile
install: npm install
before_script:
  - greenkeeper-lockfile-update
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run test

after_script:
  - greenkeeper-lockfile-upload
  - ./cc-test-reporter after-build --coverage-input-type lcov --exit-code $TRAVIS_TEST_RESULT

after_success:
  - npm run semantic-release

